### ISSUE TITLE
Two or more scripts can't tag the same objects, even from different mods

### ISSUE THREAD

**Issue by THDigi** [KeenSoftwareHouse/SpaceEngineers#103] opened 2015-05-19 15:31 UTC
Two mods having scripts that are attached to a block type will not both run.

And it's a 'notice' in F11 when playing offline:
```
Entity script overwritten: MyObjectBuilder_MyProgrammableBlock
```
when both are using:
```
[MyEntityComponentDescriptor(typeof(MyObjectBuilder_MyProgrammableBlock))]
```
Programmable block being an example.

This is a serious issue that breaks mods by having other mods installed, most of the time they won't even collide since scripts are filtering specific subtypeids too.

**Comment by Tyrsis** [comment] 2015-05-19 20:41
I think the key here would be subid attachment.  I think if we had a new attribute that allowed us to attach gamelogic to an objectbuilder by subtype as well as type, mods can coexist, as mods basically create new subtypes anyway in definition.

The new attribute would be for backwards compatibility.  If no matching subid gamelogic is found, default to old behavior.  This would require mods to add the new attribute, but would also allow them to not be overwritten if all types are stored by not only type but subidtype.  I looked at it briefly and it doesn't seem like too much trouble.  Just a modification in MyEntityScripts.cs to extract Types with new attribute, and a modification to MyEntityFactory.CreateEntity to assign gamelogic to blocks by subid.

**Comment by THDigi** [comment] 2015-05-20 03:24
That would still limit the usage, not all mods that attach themselves to blocks need to be unique, 2 or more scripts might just want to monitor the block's name without doing anything to the block which won't cause problems.

If mods do have colliding code then they can collaborate and make a solution, but if they're limited by the API then they have to re-make a more costly approach, looping through all ship entities to find the said blocks, probably many times a second depending on the needed accuracy.

I suggest keeping all the scripts working and add a 'Mod, Mod2, Mod3 are using scripts for Object, check for code collissions' notification for F11.

**Comment by Tyrsis** [comment] 2015-05-20 04:25
I implemented my solution, and it works well for keeping subtype gamelogic separate.  (Will actually solve a lot of mod collisions in itself, as I think most mods that have collision issues are discrete blocks that have their own subtype)

I see what you're saying about wanting to attach to the same block to monitor.  That is a difficult issue, and would require changing how MyGameLogicComponent is processed at the entity level (an entity would require the ability to have multiple MyGameLogicComponents attached to it)

**Comment by midspace** [comment] 2015-05-20 06:32
I think half the problem is that when we implement a custom cube, it has to inherit from an existing cube definition.
If it was a natural extension of an existing cube, I can understand.
But defining a completely new cube with its own logic should be stand alone.

Is anyone working on getting custom cube's working?

**Comment by Tyrsis** [comment] 2015-05-20 14:18
I agree completely, but felt it would be a lot to add.  Realistically block logic should be separated from the blocks themselves, and then added in ... in some manner to form a discrete block.   This would potentially allow overlapping of functionality in one block.  

That being said, the above problem still exists, when multiple scripts want to just passively monitor an existing block type, one is of them is going to be out of luck.  Maybe this can be avoided by using events instead of inheritance?

**Comment by Tyrsis** [comment] 2015-05-22 13:30
I addressed the issue in #142 so that not only can you attach only to subtypes you care about, but also allow multiple attachments of gamelogic.  I also give a warning in log about collisions, but all gamelogic will run.  I'm not married to this code either, but it fixes the issue.

**Comment by harag-on-steam** [comment] 2015-05-22 17:09
I had a look at #142 and would like to clarify what would constitute a breaking change? As far I can tell these should still be true afterwards:
 1. scripts are `MyGameLogicComponents`
 1. scripts register themselves via `[MyEntityComponentDescriptor]`

Would these also break mods?
 * add SubtypeId to MyEntityComponentDescriptor with a default value of "" (for "don't care")
 * making `MyEntity.GameLogic` non-public

**Comment by Tyrsis** [comment] 2015-05-22 18:18
I don't want to hide GameLogic.  It was used externally before, and there really is no reason to hide it right now.

I added subtypename to EntityComponentDescriptor and removed the new attribute.  I originally did a new attribute because I didn't want to disturb anything in case it broke mods.  But it looks like my changes seem fine and are backwards compatible.

**Comment by Tyrsis** [comment] 2015-05-25 17:49
I merged in some much cleaner code from harag.  I decided after some testing that enumerating really didn't matter enough not to just keep it as a collection like harag did it, so I just went with his cleaner implementation, and then fixed up some bugs (that had to do with containers, that I didn't know about at the time).  It works now with multiple mods attaching to the same type or subtype, or any combination within, basically eliminating this limitation that was there before.

**Closed** 2015-05-29 13:32 UTC
